### ISSUE TITLE
Use of -[NSString containsString:] which is unavailable in iOS 7

### ISSUE THREAD

**Issue by ghugues** [nst/RuntimeBrowser#14]
-[NSString containsString:] although very convenient is only available in iOS 8 or OS X 10.10.
If you maintain support for iOS 7, you should use -[NSString rangeOfString:]

if ([string containsString:substring]) {}

can be replaced by :

if ([string rangeOfString:substring].location != NSNotFound) {}

**Comment by MosheBerman** [comment]
This can be closed now, afaik.
