### ISSUE TITLE
how to install on iphone ?

### ISSUE THREAD

**Issue by fattalgazi** [nst/RuntimeBrowser#16]
Sorry for that question but I don't understand how can I install this to iphone ?

**Comment by MosheBerman** [comment]
You can check out the repository from GitHub on your local machine with 

`git clone https://github.com/nst/RuntimeBrowser.git`

Then open the Xcode project. Build and run it.

**Comment by AnonymiOS** [comment]
How do I use this for iOS 9.3.3? I have the app on my phone but I don't know how to get the headers off of it.

**Comment by nst** [comment]
http://stackoverflow.com/questions/26856887/runtimebrowser-class-dumping/30620645#30620645
