### ISSUE TITLE
can't see the details of classes and protocolscan't see the details of classes and protocols

### ISSUE THREAD

**Issue by MemoryReload** [nst/RuntimeBrowser#27]
When I checked out the master branch of this project and built it for OS X, I just received a syntax error  
associated with __weak qualifier. I think the code is no problem, but I don't know why the compiler complains about it.  And further more, when I ran the project on iOS, I just can't  open the detail page of classes and protocols header file. Any clue will be appropriated. Thanks.
<br/>
![iphoneerror1](https://user-images.githubusercontent.com/6024370/28869164-739dab0c-77ae-11e7-9753-860bc4490113.PNG)
<br/>
![iphoneerror2](https://user-images.githubusercontent.com/6024370/28869166-73f510e0-77ae-11e7-9283-37a18ef69181.PNG)
<br/>
![iphoneerror3](https://user-images.githubusercontent.com/6024370/28869165-73efa40c-77ae-11e7-9109-fc9c21d4ce61.PNG)
<br/>
![iphoneerror4](https://user-images.githubusercontent.com/6024370/28869167-73f70e72-77ae-11e7-816b-8db686c6fd70.PNG)
![macosxerror](https://user-images.githubusercontent.com/6024370/28869168-73f8802c-77ae-11e7-947c-6d06f789ce7f.png)

**Comment by michaeldong** [comment]
yes,i meet same question.  i use the "about" info, use PC chrome to open it . it works.

**Comment by MemoryReload** [comment]
@michaeldong  Sorry to rely for you so late. I tried the browser retrieve plan, it works. But for the native plan, it seems some problems there.

**Comment by MemoryReload** [comment]
If your also encountered this problem, please go and look at issue #6 .
