### ISSUE TITLE
Tapping a class on iPhone (iOS 7 project) does nothing

### ISSUE THREAD

**Issue by MP0w** [nst/RuntimeBrowser#6]
Not sure if it is normal or not, but when I tap on a class it isn't showed.
In some cases there isn't any didSelectRow... so I think is not a bug.
I fixed that for me do you want a pull or not?

**Comment by MemoryReload** [comment]
@nst Aha, this post save my ass! But I think writing this instruction in README.md maybe very helpful. And I think if we add an cell "info" accessory view for opening the header details, and leave the selection for displaying subclasses, it would be  better to use.
